### ISSUE TITLE
API Guide pointing to incorrect page

### ISSUE THREAD

**Issue by dstaab** [concur/developer.concur.com#606] opened 2016-07-17 21:37 UTC
This link is pointing to an incorrect page when it should be pointing to a page called, "3. How to Identify Group Codes for Standard Edition Clients"

https://developer.concur.com/api-guides/expense/3how-to-identify-group-codes-for-standard-edition-clients.html

It is pointing to an existing page called, "2. How to Provision a Basic User Record Into Concur"

I believe the attached file was submitted originally, but just in case it is attached here.
[3. How to Identify Group Codes for Standard Edition Clients.pdf](https://github.com/concur/developer.concur.com/files/368146/3.How.to.Identify.Group.Codes.for.Standard.Edition.Clients.pdf)

Please advise if you have questions.

**Comment by henryyamamoto-concur** [comment] 2016-07-18 16:49
Body content was correct. The header was wrong. Fixed in preview and will push to live once confirmed.

**Comment by henryyamamoto-concur** [comment] 2016-07-18 17:28
Upon further review when checking the build in preview, this page really doesn't look right. The PDF referenced in the issue above also looks to be not formatted correctly. Before I try to match what the PDF looks like, can @dstaab verify what we want the page to look like? The body content looks correct if you go to the page (since header was corrected). But it definitely isn't formatting correctly.

**Comment by dstaab** [comment] 2016-07-19 06:26
this tool needs to accept common outline formatting that any common word processor can support !

**Comment by henryyamamoto-concur** [comment] 2016-08-26 22:41
I think we've finally fixed this a few weeks ago.

**Closed by henryyamamoto-concur** 2016-08-26 22:41 UTC
