### ISSUE TITLE
Font size is inconsistent onhttp://preview.developer.concur.com/api-reference/authentication/authentication.html

### ISSUE THREAD

**Issue by tjohans** [concur/developer.concur.com#85] opened 2015-08-19 22:10 UTC
Some text is in 10.5pts and some is in 11pts

**Comment by henryyamamoto-concur** [comment] 2015-08-19 22:33
Dupe of #83

**Comment by henryyamamoto-concur** [comment] 2015-08-20 20:28
Fixed with afcd21d4374488439b4e7e43aba97a49dd17507c

**Closed by henryyamamoto-concur** 2015-08-20 20:28 UTC
Labels: duplicate
